services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongo'
    environment:
      - 'MONGO_INIT DB_DATABASE=product-service'
      - 'MONGO_INIT DB_ROOT_PASSWORD=password'
      - 'MONGO_INIT DB_ROOT_USERNAME=admin'
    ports:
      - '27017:27017'
    volumes:
      - ./docker/mongodb/data:/data/db
volumes:
  db:
    driver:
      local
